b=ones(1,5);
a=[1];
d=[1,-1];
f=[1];
w=0:.01:2*pi;
[h,ph]=freqz(b,a,w);
[h1,ph1]=freqz(d,f,w);
magh=abs(h);
angh=angle(h);
angh1=angle(h1);
magh1=abs(h1);
subplot(2,2,1);plot(ph/pi,magh);
ylabel('Magnitude');xlabel('Normalised Frequency');
subplot(2,2,2);plot(ph1/pi,abs(h1));
ylabel('Magnitude');xlabel('Normalised Frequency');
subplot(2,2,3);plot(ph/pi,angh);
xlabel('Normalised Frequency');ylabel('phase in radians');
subplot(2,2,4);plot(ph1/pi,angh1);
xlabel('Normalised Frequency');ylabel('phase in radians');
