x=0:.1:10;
y=gaussmf(x,[0.5 5]);
z=gaussmf(x,[0.5 7]);
a=min(1,y+z);
subplot(2,1,1):plot(x,y,'g-',x,z,'r--');
xlabel('Fuzzy Set A,B');
ylabel('Membership Grades');
subplot(2,1,2):plot(x,a);
axis([0 10 0 1]);
xlabel('Union using Bounded Sum');
ylabel('Membership Grades');